# Generated by Django 4.1.3 on 2022-11-19 06:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RegisterComplaint',
            fields=[
                ('user', models.OneToOneField(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegisterLabour',
            fields=[
                ('user', models.OneToOneField(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('labourType', models.CharField(choices=[('FL', 'Farm Labour'), ('TL', 'Transportation Labour'), ('SF', 'Scientific Farming')], max_length=50)),
                ('internship_domain', models.CharField(default='', max_length=50)),
                ('ok', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RequestLabour',
            fields=[
                ('user', models.OneToOneField(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('quantity', models.IntegerField(default='')),
                ('work_type', models.CharField(max_length=50)),
                ('date', models.DateField()),
            ],
        ),
    ]
